#!/usr/bin/env node
// Builds CH-UI with an absolute base URL (so all JS/CSS/asset requests
// resolve against that static host, not the ClickHouse host) and wraps the
// resulting dist/index.html into a <http_server_default_response> snippet
// for ClickHouse's config.d/, so ClickHouse's own HTTP port can serve the
// SPA shell while the static assets are served from S3 (or any static host).
//
// Usage:
//   node scripts/build-static.mjs --base-url=https://your-bucket.example/ch-ui/
//   S3_BASE_URL=https://your-bucket.example/ch-ui/ node scripts/build-static.mjs
//
// Options:
//   --base-url=URL     required. Public URL assets will be served from.
//   --out-dir=DIR      build output dir (default: dist)
//   --config-out=FILE  where to write the ClickHouse XML snippet
//                      (default: <out-dir>/clickhouse-http-default-response.xml)
//   --skip-build       reuse an existing build in --out-dir instead of
//                      re-running `vite build`
//
// The entry JS/CSS are additionally copied to a fixed "index-latest.*" name
// and index.html is pointed at that name instead of its content hash, so the
// generated ClickHouse config snippet never changes across rebuilds — only
// re-uploading the static files is needed after that.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(fileURLToPath(import.meta.url), "../..");

function parseArgs(argv) {
  const args = {};
  for (const arg of argv) {
    const match = /^--([^=]+)(?:=(.*))?$/.exec(arg);
    if (match) args[match[1]] = match[2] ?? true;
  }
  return args;
}

const args = parseArgs(process.argv.slice(2));

const baseUrlRaw = args["base-url"] || process.env.S3_BASE_URL;
if (!baseUrlRaw) {
  console.error(
    "Missing base URL.\n\n" +
      "Pass the public URL your static assets will be served from, e.g.:\n" +
      "  node scripts/build-static.mjs --base-url=https://your-bucket.example/ch-ui/\n" +
      "  S3_BASE_URL=https://your-bucket.example/ch-ui/ node scripts/build-static.mjs\n"
  );
  process.exit(1);
}
const baseUrl = baseUrlRaw.endsWith("/") ? baseUrlRaw : `${baseUrlRaw}/`;
if (!/^https?:\/\//.test(baseUrl)) {
  console.error(`base-url must be an absolute http(s) URL, got: ${baseUrl}`);
  process.exit(1);
}

const outDir = path.resolve(rootDir, args["out-dir"] || "dist");
const configOut = path.resolve(
  rootDir,
  args["config-out"] || path.join(outDir, "clickhouse-http-default-response.xml")
);
const indexHtmlPath = path.join(outDir, "index.html");

if (!args["skip-build"]) {
  console.log(`Building CH-UI with base URL: ${baseUrl}`);
  execFileSync(
    path.join(rootDir, "node_modules", ".bin", "vite"),
    ["build", "--outDir", outDir],
    {
      cwd: rootDir,
      stdio: "inherit",
      env: { ...process.env, VITE_BASE_PATH: baseUrl },
    }
  );
}

if (!existsSync(indexHtmlPath)) {
  console.error(`index.html not found at ${indexHtmlPath}`);
  process.exit(1);
}

let indexHtml = readFileSync(indexHtmlPath, "utf8");

// Pin the entry JS/CSS to a fixed name instead of their content hash, and
// point index.html at that name. Renames (doesn't copy) the hashed file —
// nothing else references the entry by its hash, unlike dynamically-imported
// chunks, which are referenced by hash from inside the entry bundle itself,
// not from index.html, and are left untouched.
function pinEntryAsset(html, extension) {
  const attr = extension === "js" ? "src" : "href";
  const pattern = new RegExp(`${attr}="([^"]*assets/index-[^"]+\\.${extension})"`);
  const match = html.match(pattern);
  if (!match) return html;

  const url = match[1];
  const fileName = url.slice(url.lastIndexOf("/") + 1);
  const stableFileName = `index-latest.${extension}`;
  if (fileName !== stableFileName) {
    renameSync(
      path.join(outDir, "assets", fileName),
      path.join(outDir, "assets", stableFileName)
    );
  }
  const stableUrl = url.slice(0, url.lastIndexOf("/") + 1) + stableFileName;
  return html.split(url).join(stableUrl);
}

indexHtml = pinEntryAsset(indexHtml, "js");
indexHtml = pinEntryAsset(indexHtml, "css");
writeFileSync(indexHtmlPath, indexHtml);

// Escape "]]>" so it can't prematurely close the CDATA section.
const cdataSafeHtml = indexHtml.split("]]>").join("]]]]><![CDATA[>");

const outDirRel = path.relative(rootDir, outDir);
const configOutName = path.basename(configOut);

const xml = `<?xml version="1.0"?>
<!--
  Generated by scripts/build-static.mjs, do not edit by hand, regenerate instead.
  Static assets referenced by this page (assets slash star, logo.png) are
  expected at: ${baseUrl}
  See the build-static.mjs console output for upload and install instructions.
-->
<clickhouse>
    <http_server_default_response><![CDATA[${cdataSafeHtml}]]></http_server_default_response>
</clickhouse>
`;

writeFileSync(configOut, xml);

console.log(`Wrote ClickHouse config snippet to ${path.relative(rootDir, configOut)}`);
console.log(`Base URL baked into index.html: ${baseUrl}`);
console.log(
  `\nNext steps:\n` +
    `  1. Upload everything under ${outDirRel}/ EXCEPT index.html and ${configOutName} to ${baseUrl}\n` +
    `     e.g. (S3-compatible storage):\n` +
    `       aws s3 sync "${outDirRel}" s3://<bucket>/<prefix>/ --exclude index.html --exclude ${configOutName}\n` +
    `  2. Copy ${path.relative(rootDir, configOut)} to ClickHouse's config.d/ ` +
    `(e.g. /etc/clickhouse-server/config.d/ch-ui-static.xml) and restart/reload the server.\n` +
    `  3. Visiting the ClickHouse HTTP interface root (e.g. http://<host>:8123/) will now serve ` +
    `the CH-UI SPA shell, which loads its JS/CSS from ${baseUrl}\n`
);
